webapps/urls.py
from django.contrib import admin
from django.urls import path, include
from werewolves import views

urlpatterns = [
    path('', views.login_action),
    path('werewolves/', include('werewolves.urls')),
]

werewolves/urls.py
from django.urls import path
from werewolves import views

urlpatterns = [
    path('', views.login_action, name='home'),
    path('login', views.login_action, name='login'),
    path('rules', views.rulespage_action, name='rules'),
    path('waitingroom', views.waitingroom_action, name='waitingroom'),
    path('logout', views.logout_action, name='logout'),
    path('register', views.register_action, name='register'),
    path('game', views.start_game_action, name='game'),
]

werewolves/models.py
from django.db import models
from django.contrib.auth.models import User
from enum import Enum

# A Player can have four different roles, plus one unassigned:
class PlayerRole(Enum):
    VILLAGER = "VILLAGER"
    WOLF     = "WOLF"
    SEER     = "SEER"
    GUARD    = "GUARD"
    NONE     = "NOT ASSIGNED"

    @classmethod
    def choices(cls):
        return tuple((i.name, i.value) for i in cls)

# A game procedure has multiple steps, plus one unassigned:
class GameStep(Enum):
    WOLF = "WOLF" # wolf select target
    #END_KILL = "END_KILL" # wolf finished kill
    GUARD = "GUARD" # guard select target
    SEER = "SEER" # seer select target
    #END_NIGHT = "END_NIGHT"  # update killing at night status
    ANNOUNCE = "ANNOUNCE" # announce game status and last night killed status
    SPEECH = "SPEECH" # every player make a speech
    #END_SPEECH = "END_SPEECH" # end speech
    VOTE = "VOTE" # start voting
    END_VOTE = "END_VOTE" #annouce voting status
    END_DAY = "END_DAY" # clean all data at this step
    END_GAME = "END_GAME"  # Game Over
    NONE = "NOT ASSIGNED"

    @classmethod
    def choices(cls):
        return tuple((i.name, i.value) for i in cls)

# A Player can have three statuses.
class PlayerStatus(Enum):
    ALIVE = "ALIVE"
    OUT   = "OUT" # attacked by the wolves or voted out by other players

    @classmethod
    def choices(cls):
        return tuple((i.name, i.value) for i in cls)

# The Player model keeps track of the player's username and role.
class Player(models.Model):
    # Username must be shorter than 30 characters.
    user     = models.ForeignKey(User, on_delete=models.PROTECT, related_name="player", null=True)
    role     = models.CharField(max_length=30, choices=PlayerRole.choices(), default="NONE")
    status   = models.CharField(max_length=30, choices=PlayerStatus.choices(), default="ALIVE")
    #vote     = models.ForeignKey('self', on_delete=models.CASCADE, related_name='voted', null=True)
    vote     = models.IntegerField(null=True)
    kill     = models.IntegerField(null=True)
    # TODO: Tentative field, indicate whether a player is making a speech or not
    speech   = models.BooleanField(default=False)
    id_in_game = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return 'Player' + str(self.id_in_game) +  ": " + self.role


class Message(models.Model):
    message_text = models.CharField(max_length=200)
    message_sender = models.ForeignKey(User, on_delete=models.PROTECT, related_name="message_creator")

    def __str__(self):
        return 'Message(id=' + str(self.id) + ')'

class GameStatus(models.Model):
    wolves_select = models.IntegerField(null=True)
    guard_select = models.IntegerField(null=True)
    guard_previous_id       = models.IntegerField(null=True)
    seer_select = models.IntegerField(null=True)
    seer_target_role        = models.CharField(max_length=30, null=True, default="NONE")
    vote_select             = models.IntegerField(null=True)
    first_speaker_id        = models.IntegerField(null=True)
    speaker_id = models.IntegerField(null=True)
    current_speaker_role    = models.CharField(max_length=30, null=True, default="NONE")
    step            = models.CharField(max_length=30, choices=GameStep.choices(), default=GameStep.NONE)
    # Indicate if the game is over, False: wolves win, True: good people win, None: game is not over
    winning         = models.BooleanField(null=True, default=None)
    wolves          = models.CharField(max_length=6, null=True, blank=True)
    seer            = models.CharField(max_length=6, null=True, blank=True)
    guard           = models.CharField(max_length=6, null=True, blank=True)
    villagers       = models.CharField(max_length=6, null=True, blank=True)
    vote            = models.CharField(max_length=6, null=True, blank=True)
    is_kill         = models.CharField(max_length=6, null=True, blank=True)

    trigger_id      = models.IntegerField(null=True)

werewolves/forms.py
from django import forms

from django.contrib.auth import authenticate
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(max_length=200, widget=forms.PasswordInput())

    # Customizes form validation for properties that apply to more
    # than one field.  Overrides the forms.Form.clean function.
    def clean(self):
        # Calls our parent (forms.Form) .clean function, gets a dictionary
        # of cleaned data as a result
        cleaned_data = super().clean()

        # Confirms that the two password fields match
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if not user:
            raise forms.ValidationError("Invalid username/password")

        # We must return the cleaned data we got from our parent.
        return cleaned_data


class RegisterForm(forms.Form):
    username = forms.CharField(max_length=20)
    email = forms.CharField(max_length=50,
                            widget=forms.EmailInput())
    password = forms.CharField(max_length=200,
                               label='Password',
                               widget=forms.PasswordInput())
    confirm_password = forms.CharField(max_length=200,
                                       label='Confirm password',
                                       widget=forms.PasswordInput())

    # Customizes form validation for properties that apply to more
    # than one field.  Overrides the forms.Form.clean function.
    def clean(self):
        # Calls our parent (forms.Form) .clean function, gets a dictionary
        # of cleaned data as a result
        cleaned_data = super().clean()

        # Confirms that the two password fields match
        password1 = cleaned_data.get('password')
        password2 = cleaned_data.get('confirm_password')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords did not match.")

        # We must return the cleaned data we got from our parent.
        return cleaned_data

    # Customizes form validation for the username field.
    def clean_username(self):
        # Confirms that the username is not already present in the
        # User model database.
        username = self.cleaned_data.get('username')
        if User.objects.filter(username__exact=username):
            raise forms.ValidationError("Username is already taken.")

        # We must return the cleaned data we got from the cleaned_data
        # dictionary
        return username

werewolves/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse
from django.views.decorators.csrf import ensure_csrf_cookie

from werewolves.forms import LoginForm, RegisterForm
from werewolves.models import Player

@login_required
def rulespage_action(request):
    if request.method == 'GET':
        player_count = Player.objects.count()
        # TODO: change to player_count >= 6
        if player_count >= 6:
            context = { 'enable_button': False }
        else:
            context = { 'enable_button': True }
        return render(request, 'werewolves/rules.html', context)

@login_required
@ensure_csrf_cookie
def waitingroom_action(request):
    if request.method == 'GET':
        player_count = Player.objects.count()
        context = {}
        if player_count >= 6:
            # If there are more than 6 players, do not allow new player
            # to enter the waiting room
            context['enable_button'] = False
            return render(request, 'werewolves/rules.html', context)
        else:
            return render(request, 'werewolves/waitingroom.html', context)

@login_required
@ensure_csrf_cookie
def start_game_action(request):
    if request.method == 'GET':
        # get the role of the current player
        requestPlayer = Player.objects.get(user=request.user)
        context = {}
        context['identity'] = requestPlayer.role
        # get all the players, so that front end can update the canvas avatars accordingly
        # get the number and username of all the players
        # to avoid the situation when the player id is random in the database, we will manually create id
        players = Player.objects.all()
        for player in players:
                id = str(player.id_in_game)
                context['num' + id ] = id
                context['username' + id] = player.user.username
                if requestPlayer.role == "WOLF" and player.role == "WOLF":
                    context['avatar'+ id] = "werewolves/images/bad_avatar.png"
                else:
                    context['avatar'+ id] = "werewolves/images/good_avatar.png"
        # show different avatars
        return render(request, 'werewolves/game.html', context)


def login_action(request):
    context = {}
    # Just display the login form if this is a GET request.
    if request.method == 'GET':
        context['form'] = LoginForm()
        return render(request, 'werewolves/login.html', context)

    # Creates a bound form from the request POST parameters and makes the
    # form available in the request context dictionary.
    form = LoginForm(request.POST)
    context['form'] = form

    # Validates the form.
    if not form.is_valid():
        return render(request, 'werewolves/login.html', context)

    new_user = authenticate(username=form.cleaned_data['username'],
                            password=form.cleaned_data['password'])

    login(request, new_user)

    return redirect(reverse('rules'))


def logout_action(request):
    logout(request)
    return redirect(reverse('login'))


def register_action(request):
    context = {}

    # Just display the registration form if this is a GET request.
    if request.method == 'GET':
        context['form'] = RegisterForm()
        return render(request, 'werewolves/register.html', context)

    # Creates a bound form from the request POST parameters and makes the
    # form available in the request context dictionary.
    form = RegisterForm(request.POST)
    context['form'] = form

    # Validates the form.
    if not form.is_valid():
        return render(request, 'werewolves/register.html', context)

    # At this point, the form data is valid.  Register and login the user.
    new_user = User.objects.create_user(username=form.cleaned_data['username'],
                                        password=form.cleaned_data['password'],
                                        email=form.cleaned_data['email'])
    new_user.save()
    new_user = authenticate(username=form.cleaned_data['username'],
                            password=form.cleaned_data['password'])

    login(request, new_user)
    return redirect(reverse('login'))

werewolves/templates/werewolves/base.html
<html>
<head>
    <meta charset="utf-8">
    {% load static %}
    <link href="{% static 'werewolves/base.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="shortcut icon" href="#" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'werewolves/werewolves.js' %}" type="text/javascript"></script>
    <title> WereWolves </title>
</head>

<body>

<div class="big-heading">
     <span id="id_name_of_site"> WereWolves </span> <span>
    {% block heading %}
    {% endblock %}
    <hr/>
</div>

{% if message %}
<div class="message" id="message">
    {{message}}
</div>
{% endif %}

<!--all the conten†s go into this block-->
<div class="content">
    {% block content %}
    {% endblock %}
</div>

</body>
</html>

werewolves/templates/werewolves/game.html
{% extends "werewolves/base.html" %}
{% load static %}

{% block heading %}
<span id="id_logged_in_username">{{user.username}}</span>
{% endblock %}

{% block content %}
<div>
    <form method="get" action="{% url 'rules' %}">
        <button class="hidden_buttons buttons log-out" style="display: none" id="id_end_game_hidden_button" disabled>Exit the Game</button>
        <span id="error" class="error"></span>
    </form>
</div>
<div class="container">
    <div class="row" id="canvas">
        <div class="col-md-12 col-lg-12">
            <div class="game col-md-8 col-lg-8">
                <div class="row justify-content-center" id="identity">
                    Your identity is: {{identity}}
                </div>

                <div class="row avatar-row justify-content-center" id="avatars_row_1">
                    <div class="col-md-3 col-lg-3">
                    </div>
                    <div class="col-md-4 col-lg-4">
                        <a href="#" onclick="selectPlayer(1)" id="player_1_avatar_link">
                            <img id="avatar_1_img" src="{% static avatar1 %}" alt="player 1">
                        </a>
                    </div>
                    <div class="col-md-3 col-lg-3">
                    </div>
                </div>

                <div class="row username-row justify-content-center" id="username_row_1">
                    <div class="col-md-3 col-lg-3">
                    </div>
                    <div class="col-md-4 col-lg-4">
                        <div class="username" id="player_1_name">
                            {{num1}} {{username1}}
                        </div>
                    </div>
                    <div class="col-md-3 col-lg-3">
                    </div>
                </div>

                <div class="row botton-row justify-content-center" id="button_row_1">
                    <div class="col-md-4 col-lg-4">
                    </div>
                    <div class="col-md-4 col-lg-4">
                        <div class='button-container' id="confirm_button_container_1">
                            <button class="hidden_buttons confirm-button" onclick="updateGameStatus(1)" style="display: none" id="confirm_button_1" disabled>confirm</button>
                        </div>
                    </div>
                    <div class="col-md-3 col-lg-3">
                    </div>
                </div>

                <div class="row avatar-row justify-content-center" id="avatars_row_2">
                    <div class="col-md-2 col-lg-2">
                        <a href="#" onclick="selectPlayer(2)" id="player_2_avatar_link">
                            <img id="avatar_2_img" src="{% static avatar2 %}" alt="player 2">
                        </a>
                    </div>
                    <div class="col-md-6 col-lg-6" id="show_end_game">

                    </div>
                    <div class="col-md-1 col-lg-2">
                        <a href="#" onclick="selectPlayer(6)" id="player_6_avatar_link">
                            <img id="avatar_6_img" src="{% static avatar6 %}" alt="player 6">
                        </a>
                    </div>
                </div>

                <div class="row username-row justify-content-center" id="username_row_2">
                    <div class="col-md-2 col-lg-2">
                        <div class="username" id="player_2_name"> {{num2}} {{username2}}</div>
                    </div>
                    <div class="col-md-6 col-lg-6">
                    </div>
                    <div class="col-md-1 col-lg-2">
                        <div class="username" id="player_6_name"> {{num6}} {{username6}}</div>
                    </div>
                </div>

                <div class="row button-row justify-content-center" id="button_row_2">
                    <div class="col-md-2 col-lg-2">
                        <div class='button-container' id="confirm_button_container_2">
                            <button class="hidden_buttons confirm-button" onclick="updateGameStatus(2)" style="display: none" id="confirm_button_2" disabled>confirm</button>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-6">
                    </div>
                    <div class="col-md-1 col-lg-2">
                        <div class='button-container' id="confirm_button_container_6">
                            <button class="hidden_buttons confirm-button" onclick="updateGameStatus(6)" style="display: none" id="confirm_button_6" disabled>confirm</button>
                        </div>
                    </div>
                </div>

                <div class="row avatar-row justify-content-center" id="avatars_row_3">
                    <div class="col-md-2 col-lg-2">
                        <a href="#" onclick="selectPlayer(3)" id="player_3_avatar">
                            <img id="avatar_3_img" src="{% static avatar3 %}" alt="player 3">
                        </a>
                    </div>
                    <div class="col-md-6 col-lg-6">
                    </div>
                    <div class="col-md-2 col-lg-2">
                        <a href="#" onclick="selectPlayer(5)" id="player_5_avatar_link">
                            <img id="avatar_5_img" src="{% static avatar5 %}" alt="player 5">
                        </a>
                    </div>
                </div>


                <div class="row username-row justify-content-center" id="usename_row_3">
                    <div class="col-md-2 col-lg-2">
                        <div class="username" id="player_3_name"> {{num3}} {{username3}}</div>
                    </div>
                    <div class="col-md-4 col-lg-6">
                    </div>
                    <div class="col-md-2 col-lg-2">
                        <div class="username" id="player_5_name"> {{num5}} {{username5}}</div>
                    </div>
                </div>


                <div class="row button-row justify-content-center" id="button_row_3">
                    <div class="col-md-2 col-lg-2">
                        <div class='button-container' id="confirm_button_container_3">
                            <button class="hidden_buttons confirm-button" onclick="updateGameStatus(3)" style="display: none" id="confirm_button_3" disabled>confirm</button>
                        </div>
                    </div>
                    <div class="col-md-4 col-lg-6">
                    </div>
                    <div class="col-md-2 col-lg-2">
                        <div class='button-container' id="confirm_button_container_5">
                            <button class="hidden_buttons confirm-button" onclick="updateGameStatus(5)" style="display: none" id="confirm_button_5" disabled>confirm</button>
                        </div>
                    </div>
                </div>


                <div class="row avatar-row justify-content-center" id="avatars_row_4">
                    <div class="col-md-3 col-lg-3">
                    </div>
                    <div class="col-md-4 col-lg-4">
                        <a href="#" onclick="selectPlayer(4)" id="player_4_avatar_link">
                            <img id="avatar_4_img" src="{% static avatar4 %}" alt="player 4">
                        </a>
                    </div>
                    <div class="col-md-3 col-lg-3">
<!--                        button to press after finishing speaking -->
                        <button class="hidden_buttons" onclick="updateGameStatus(null)" style="display: none" id="next_step_button" disabled>Skip Action</button>
                    </div>
                </div>

                <div class="row username-row justify-content-center" id="username_row_4">
                    <div class="col-md-3 col-lg-3">
                    </div>
                    <div class="col-md-4 col-lg-4">
                        <div class="username" id="player_4_name"> {{num4}} {{username4}}</div>
                    </div>
                    <div class="col-md-3 col-lg-3">
                    </div>
                </div>

                <div class="row button-row justify-content-center" id="button_row_4">
                    <div class="col-md-4 col-lg-4">
                    </div>
                    <div class="col-md-4 col-lg-4">
                        <div class='button-container' id="confirm_button_container_4">
                            <button class="hidden_buttons confirm-button" onclick="updateGameStatus(4)" style="display: none" id="confirm_button_4" disabled>confirm</button>
                        </div>
                    </div>
                    <div class="col-md-3 col-lg-3">
                    </div>
                </div>

            </div>


            <div class="chat col-md-4 col-lg-4 d-flex flex-column justify-content-between">
                <div class="col" id="game_chat_title">
                    Game Chat
                </div>
                <div class="col">
                    <div id="chatbox">
                        <ul id="chat-message-list" style="list-style-type:none">
                        </ul>
                    </div>
                </div>
                <div class="col">
                    <input type="text" id="message_input"/>
                </div>
                <div class="col">
                    <button class="buttons" id="message_button" onclick="sendMessage()">Send</button>
                </div>
<!--                <div class="col">-->
<!--                    <button class="buttons" id="message_button" onclick="nextStep()">Next Step</button>-->
<!--                </div>-->
                <div class="col" id="id_timer"> 
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

werewolves/templates/werewolves/login.html
{% extends "werewolves/base.html" %}

{% block content %}
<div id="login_page">
    <form method="post" action="{% url 'login' %}">
        <table>
            <tr>
                <th><label for="id_username" class="labels">Username:</label></th>
                <td><input type="text" name="username" maxlength="20" required id="id_username" class="fields"></td>
            </tr>
            <tr>
                <th><label for="id_password" class="labels">Password:</label></th>
                <td><input type="password" name="password" maxlength="200" required id="id_password" class="fields">
                </td>
            </tr>
        </table>
        {% csrf_token %}
        <button type="submit" class="buttons" id="id_login_button">Log In</button>
    </form>

    <div>
        <a href="{% url 'register' %}" class="loginregister-link" id="id_register_link">
            Register
        </a>
    </div>
</div>

{% endblock %}

werewolves/templates/werewolves/register.html
{% extends "werewolves/base.html" %}

{% block content %}
<div id="register_page">

    <form method="post" action="{% url 'register' %}">
        <table class="table-content">
            <tr>
                <td class="labels"><label for="id_username">Username:</label></td>
                <td><input type="text" name="username" maxlength="20" class="fields" required id="id_username"></td>
                <td class="errorlist">

                </td>
            </tr>

            <tr>
                <td class="labels"><label for="id_email">Email:</label></td>
                <td><input type="email" name="email" maxlength="50" class="fields" required id="id_email"></td>
                <td class="errorlist">

                </td>
            </tr>

            <tr>
                <td class="labels"><label for="id_password">Password:</label></td>
                <td><input type="password" name="password" class="fields" maxlength="200" required id="id_password">
                </td>
                <td class="errorlist">

                </td>
            </tr>

            <tr>
                <td class="labels"><label for="id_confirm_password">Confirm password:</label></td>
                <td><input type="password" name="confirm_password" maxlength="200" class="fields" required
                                          id="id_confirm_password"></td>
                <td class="errorlist">

                </td>
            </tr>
        </table>
        {% csrf_token %}
        <button type="submit" class="buttons" id="id_register_button">Register</button>
    </form>

    <div>
        <a href="{% url 'login' %}" class="loginregister-link" id="id_login_link">
            Login
        </a>
    </div>

    {% for error in form.non_field_errors %}
    <p class="errorlist">
        {{ error }}
    </p>
    {% endfor %}
</div>

{% endblock %}

werewolves/templates/werewolves/rules.html
{% extends "werewolves/base.html" %}

{% block heading %}
<span id="id_logged_in_username">{{user.username}}</span>
{% endblock %}

{% block content %}
<h1><b>Rules for the Werewolves Game</b></h1>
<br>
<h3><b>Players</b></h3>
Werewolves is a board game with 6 players. The players are divided into two camps: 2 in the Wolf camp and 4 in the Good People camp. 
<br>
<br>
<h3><b>Player Roles</b></h3>
Players in the Wolf camp only have Wolf roles. On the other hand, the Good People Camp consists of 3 different roles: 2 Villagers, 
1 Seer and 1 Guard. 
<br>
<br>
<h3><b>Game Procedures</b></h3>
The game has two phases: Night and Day. 
<br>
<br>
<h3><b>Night</b></h3>
At Night, players in the Wolf camp discuss among themselves and select a player to kill in the Good People camp. Players in the 
Wolf camp have their identities hidden from the other players. Next, the Seer can check the camp of one player. After that, the 
Guard is told of which player is killed that night and can choose whether to protect the player or not. If the player who is killed 
is not protected by the Guard, that player will have to leave the game.
<br>
<br>
<h3><b>Day</b></h3>
During the Day, all players are notified of whether a players is killed last night and who that player is. Each player will make a 
speech and then all players will vote for one person. The player who gets the most votes has to leave the game. The players will 
receive system messages, make speeches and chat with each other using a chat box.
<br>
<div>
    <form method="get" action="{% url 'waitingroom' %}">
        {% if enable_button %}
            <button class="buttons" id="id_join_waiting_room_button">Join Waiting Room</button>
        {% else %}
            <button class="buttons" id="id_join_waiting_room_button" disabled>Join Waiting Room</button>
        {% endif %}
        <span id="error" class="error"></span>
    </form>
</div>
{% endblock %}

werewolves/templates/werewolves/waitingroom.html
{% extends "werewolves/base.html" %}

{% block heading %}
<span id="id_logged_in_username">{{user.username}}</span>
{% endblock %}

{% block content %}
<a href="{% url 'login' %}" class="log-out" id="id_logout" onclick="exitGame()">Exit the Game</a>
<div class="players">
    <div class="players_label"> Players: </div><br>
    <ul class="player-list" id="id_player_list">
    </ul>
</div>

<div class="player-num" id="id_player_num">
</div>

<div class="player-joined" id="id_player_join">
</div>

<div>
    <button class="buttons" style="visibility: hidden" id="id_start_game_button" onclick="sendStart()" disabled>Start Game</button>
    <form method="get" action="{% url 'game' %}">
        <button class="hidden_buttons buttons" style="visibility: hidden" id="id_start_game_hidden_button" disabled></button>
        <span id="error" class="error"></span>
    </form>
</div>

</section>

<script>
    window.setTimeout(sendJoin, 500)
</script>
{% endblock %}